<div class="container">
	<h1>Edit Data Mahasiswa</h1>
	<br>
	<?= $this->tag->form('mahasiswa/update') ?>
		<input type="hidden" name="id" value="<?= $mahasiswa->id; ?>">
		<div class="form-group">
			<label>Nama Mahasiswa</label>
			<input type="text" name="nama" required class="form-control" value="<?= $mahasiswa->nama; ?>">
		</div>
		<div class="form-group">
			<label>Alamat</label>
			<textarea name="alamat" required class="form-control"><?= $mahasiswa->alamat; ?></textarea>
		</div>
		<input type="submit" name="submit" value="Submit" class="btn btn-success">
	<?= $this->tag->endForm() ?>
</div>