<div class="container">
	<h1>CRUD Mahasiswa</h1>		
	<br>
	<?= $this->tag->form('mahasiswa/create') ?>
		<div class="form-group">
			<label>Nama Mahasiswa</label>
			<input type="text" name="nama" required class="form-control">
		</div>
		<div class="form-group">
			<label>Alamat</label>
			<textarea name="alamat" required class="form-control"></textarea>
		</div>
		<input type="submit" name="submit" value="Submit" class="btn btn-success">
	<?= $this->tag->endForm() ?>
	<br><hr><br>
	<h3>Tabel Data Mahasiswa</h3>
	<table class="table">
		<thead>
			<tr>
				<th>No.</th>
				<th>Nama</th>
				<th>Alamat</th>
				<th>Edit</th>
				<th>hapus</th>
			</tr>
		</thead>
		<tbody>
			<?php $no = 1; ?>
			<?php foreach($mahasiswas as $mahasiswa): ?>
	    <tr>
	    		<td><?= $no++; ?></td>
	        <td><?= $mahasiswa->nama; ?></td>
	        <td><?= $mahasiswa->alamat; ?></td>
	        <td><a href="mahasiswa/edit/<?= $mahasiswa->id ?>" class="btn btn-info">Edit</a></td>
	        <td><a href="mahasiswa/delete/<?= $mahasiswa->id ?>" class="btn btn-danger">Delete</a></td>
	    </tr>
	    <?php endforeach; ?>	
		</tbody>
	</table>
	<br>
</div>